### ISSUE TITLE
trace-number

### ISSUE THREAD

**Issue by korangcity** [shetabit/multipay#100]
سلام. در مد آزمایشی پرداخت زرین پال، در تنظیمات مد کاری رو سندباکس گذاشتم، سولم این بود که مقدار کد رهگیری پرداخت رو چجوری بدست بیارم؟ داکیومنت رو خوندم ولی برام جواب نداد

مرسی

**Comment by iamammiin** [comment]
سلام- بعد از کال کردن  متد وریفای می‌تونین با این فانکشن کدرهگیری رو دریافت کنین. 
طبق کد زیر : 

` $receipt = Payment::amount(1000)>transactionId($transaction_id)->verify();`
`$receipt->getReferenceId()`
