### ISSUE TITLE
Zarinpal unverified method is not implemented

### ISSUE THREAD

**Issue by erfantkerfan** [shetabit/multipay#102]
## Detailed description

Zarinpal unverified method is not implemented

## Context

reference to this method in zarinpal website: https://docs.zarinpal.com/paymentGateway/other/#unverified

**Comment by khanzadimahdi** [comment]
this method is not a member of the standard payment interface.

**Comment by erfantkerfan** [comment]
okay but it can be implemented in zarinpal directly
because its needed for using third party gateways because normal gateways will refund the money when the payment is not verified bit third party gateways will keep the money and we most verify it ourselves

**Comment by erfantkerfan** [comment]
I can make a pull request if you think there is a place for this method

**Comment by khanzadimahdi** [comment]
okay, please change the Zarinpal gateway and send a pull request.
we don't need to expose a new method called unverified!!! please create and private method and call it when verification fails.

**Comment by khanzadimahdi** [comment]
I close this issue due to being a long time inactive.
