### ISSUE TITLE
Hello, i am getting error API Key یافت نشد. on ID PAY

### ISSUE THREAD

**Issue by tobelyan** [shetabit/multipay#104]
Hello, i am getting error API Key یافت نشد.
How do i set API key for IDPay,
I have tried to set parameter API-KEY but it is obviously wrong name.

**Comment by khanzadimahdi** [comment]
please remove config cache and publish package vendors.

**Comment by tobelyan** [comment]
it is set, in the config for IDPay i have

            'apiPurchaseUrl' => 'https://api.idpay.ir/v1.1/payment',
            'apiPaymentUrl' => 'https://idpay.ir/p/ws/',
            'apiSandboxPaymentUrl' => 'https://idpay.ir/p/ws-sandbox/',
            'apiVerificationUrl' => 'https://api.idpay.ir/v1.1/payment/verify',
            'merchantId' => '',
            'callbackUrl' => 'SOME URL',
            'description' => 'payment using idpay',
            'sandbox' => true, // set it to true for test environments

so where to put the API key in these variables

**Comment by tobelyan** [comment]
i am sure i am setting wrong variable name for the api key, and btw, i am using config function for api key
Payment::callbackUrl(route('verify.payment',$order->id))->config(['api_key'=>'keyHash'])......

**Comment by tobelyan** [comment]
Ah, never mind, it was merchantID as a api key

**Comment by jpro123** [comment]
شما باید در سایت idpay ثبت نام کنین و api key از قسمت وب سرویس بگیرین و تو تنظیمات پکیج api key خودتون رو در merchantId تنظیمات اضافه کنین  
در حالت sandbox هم نیاز بهkey api  هست
