### ISSUE TITLE
بررسی مبلغ پرداختی در بانک سامان

### ISSUE THREAD

**Issue by YSSFK** [shetabit/multipay#105]
تو داکیومنت باک سامان اومده که باید بعد وریفای شدن تراکنش مبلغی که در ریسپانس برمیگرده رو با مبلغی که کاربر پرداخت کرده مقایسه کرد و اگه این دوتا باهم برابر نبود باید تراکنش ریورس بشه من کد مربوط به درایور بانک سامان رو بررسی کرد این شرط چک نمیشه.
دلیل خاصی داره اینکه چک نمیشه؟

**Comment by khanzadimahdi** [comment]
سلام. اگه حس میکنید مشکلی هست اونو فیکس کنید و درخواست مرج بدید

**Comment by iamammiin** [comment]
> تو داکیومنت باک سامان اومده که باید بعد وریفای شدن تراکنش مبلغی که در ریسپانس برمیگرده رو با مبلغی که کاربر پرداخت کرده مقایسه کرد و اگه این دوتا باهم برابر نبود باید تراکنش ریورس بشه من کد مربوط به درایور بانک سامان رو بررسی کرد این شرط چک نمیشه.
> دلیل خاصی داره اینکه چک نمیشه؟

تا اونجا که من دارم استفاده می‌کنم از این سرویس و میدونم فانکشن 
verify
فقط یه کار انجام میده و اونم اینه که درخواست وریفای کردن رو بفرسته به سمت بانک سامان .

چک کردن مبلغ برگشتی با مبلغ تراکنش داخل سیستم شما رو قبل اینکه این درخواست رو کال کنین باید خودتون انجام بدین.

**Comment by YSSFK** [comment]
> > تو داکیومنت باک سامان اومده که باید بعد وریفای شدن تراکنش مبلغی که در ریسپانس برمیگرده رو با مبلغی که کاربر پرداخت کرده مقایسه کرد و اگه این دوتا باهم برابر نبود باید تراکنش ریورس بشه من کد مربوط به درایور بانک سامان رو بررسی کرد این شرط چک نمیشه.
> > دلیل خاصی داره اینکه چک نمیشه؟
> 
> تا اونجا که من دارم استفاده می‌کنم از این سرویس و میدونم فانکشن
> verify
> فقط یه کار انجام میده و اونم اینه که درخواست وریفای کردن رو بفرسته به سمت بانک سامان .
> 
> چک کردن مبلغ برگشتی با مبلغ تراکنش داخل سیستم شما رو قبل اینکه این درخواست رو کال کنین باید خودتون انجام بدین.

تو این داکیومنت اینطوری نوشته که باید مقدار برگشتی از 
VerifyTransaction
باید با مقدار فاکتور سیستم که باید توسط کاربر پرداخت میشده برابر باشه
https://www.sep.ir/Data/Sites/1/media/epay/1.SEP-PPG-Purchase%20With%20Mobile%20Number-TechnicalSpecification%20-%20Token%20Payment.pdf
صفحه‌ی 13 تا 14

**Comment by iamammiin** [comment]
@YSSFK 

چیزی که میگین درسته ولی باید سمت خودتون هندل کنین  قبل اینکه وریفای رو صدا بزنید تابع وریفای فقط برای ارسال درخواست وریفای هست و نمیشه توش عملیات دیگه ای انجام بشه .


حتی باید کد یکتای ارسالی از سمت بانک رو هم داخل دیتابیس خودتون چک کنید که تکراری نباشه چون میشه این کد رو برداشت و برای  بقیه وریفای هایی که از سمت بانک میاد هم استفاده کرد.

**Comment by YSSFK** [comment]
@iamammiin 
نه متوجه در مورد چک کردن کد یکتا و قیمت قبل وریفای ولی ذکر شده که مقدار برگشتی ار تابع وریفای هم دوباره چک بشه و اکتفا نشه به قیمتی که توی ریدایرکت ارسال شده
یسری پکیج‌ها هم این رو پیاده کردن مثلا پکیج 
larabook gateway
اینطوری استفاده کرده که اگه ریسپانس 
verify transaction 
مثبت بود و برابر با مقدار نبود 
reverse transaction 
رو کال میکنه
ولی برای بقیه درگاه هاشون چیزی که پیاده شده مشابه حرفی هست که شما میگید

**Comment by khanzadimahdi** [comment]
@YSSFK 

کاری که مد نظرتونه انجام بدید و درخواست مرج بدید تا باهم بررسی کنیم و اگه اوکی بود مرج کنیم

**Comment by iamammiin** [comment]
@YSSFK

درسته حتما باید رعایت بشه، ولی من میگم درست نیست داخل فانکشنی که کارش ارسال درخواست وریفای و اصولا خروجیش هم باید نمایش  ریسپانس این درخواست باشه  چیز دیگه ای نوشته بشه 

حداقلش اینه فانکنش دیگه ای تعریف بشه واسه این قضیه که میگین فک کنم درست تر باشه.

**Comment by YSSFK** [comment]
@iamammiin 
بله درست میفرمایید متوجه منظورتون نشده بودم
