### ISSUE TITLE
مشکل در کار با درگاه پرداخت آفلاین 

### ISSUE THREAD

**Issue by Abtinkarimpour** [shetabit/multipay#108]
سلام در حین ریدایرکت کردن پس از پرداخت موفق اررور

Page Expired 
لاراول را برمیگرداند.

bug

* PHP 7.2, laravel 8
* Windows

**Comment by Abtinkarimpour** [comment]
در بقیه
issue
ها خوندم که پکیج 
multipay
برای کار با لاراول نیست و در پکیج
payment 
رگاه لوکال وجود ندارد اما با اضافه کردن این قطعه کد به فایل
local-form.php
درگاه پرداخت لوکال به خوبی بر روی لاراول کار میکند
```
    <form action="<?php echo(isset($inputs['successUrl']) ? htmlentities($inputs['successUrl']) : '#') ?>" method="post" id="success_form">
        <input type="hidden" name="_token" value="<?php echo csrf_token()?>">
    </form>
    <form action="<?php echo(isset($inputs['cancelUrl']) ? htmlentities($inputs['cancelUrl']) : '#') ?>" method="post" id="cancel_form">
        <input type="hidden" name="_token" value="<?php echo csrf_token()?>">
    </form>
```

**Comment by jpro123** [comment]
این مشکل پکیج نیست مشگل مربوط به تنظیمات جدید مرورگرها میشه . 

در لاراول در پوشه config فایل session.php را باز کنید . آخرین متغیر :  'same_site' => 'lax' را به 'same_site' => 'none; تغییر بدین مشکلتون حل میشه
