### ISSUE TITLE
Zarinpal sandbox has SOAP-ERROR

### ISSUE THREAD

**Issue by ssshojaei** [shetabit/multipay#11]
## Detailed description

Zarinpal sandbox has SOAP-ERROR

## Error

SoapFault
SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://sandbox.zarinpal.com/pg/services/WebGate/wsdl' : failed to load external entity "https://sandbox.zarinpal.com/pg/services/WebGate/wsdl"

## Environment

* PHP 7.3.5
* Arch Linux
* Laravel 7

**Comment by khanzadimahdi** [comment]
#10

**Comment by khanzadimahdi** [comment]
does the bug exists only in sandbox mode? please check your network again.
do you use any VPN then sending request to Zarinpal?

**Comment by ssshojaei** [comment]
I just tested on localhost and my VPN is turned off

**Comment by aminmohammadmazreali** [comment]
> I just tested on sandbox mood and my VPN is turned off

my zarinpal sandbox mode  worked true
but get this error in Saman and behpardakht gateway

**Comment by khanzadimahdi** [comment]
I think it depends on php version! the php soap works differently in each version.

**Comment by khanzadimahdi** [comment]
@aminmohammadmazreali please check if `php_openssl` is enabled or not? check the `php.ini` file please.

**Comment by khanzadimahdi** [comment]
@ssshojaei please check if `php_openssl` is enabled or not? check the `php.ini` file please.

**Comment by Obka** [comment]
have a same problem ...

**Comment by khanzadimahdi** [comment]
@Obka we have not recognized the reason of this problem yet. pull requests will we accepted. please fix it and send pull request.

**Comment by Obka** [comment]
@khanzadimahdi I did not understand the reason for this problem.
Have you corresponded with ZarrinPal Company?

**Comment by khanzadimahdi** [comment]
@Obka No! could you talk about this problem with Zarinpal company and report them this issue?

**Comment by Obka** [comment]
@khanzadimahdi I reported the problem to them a week ago, but they have not responded yet.  They probably won't answer !!

**Comment by khanzadimahdi** [comment]
hmm, take a look at below codes. if you recognize any error please share it with me to resolve the problem.

https://github.com/shetabit/multipay/blob/master/src/Drivers/Zarinpal/Zarinpal.php

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
i close this issue, if you found any bug, please fork the package and fix the bug, then create a pull request. i will merge it.
</div>
