### ISSUE TITLE
مشکل در نمایش خطا ها در درگاه بانک سامان

### ISSUE THREAD

**Issue by 95moja71** [shetabit/multipay#113]
در دایور بانک سامان خطاهای مربوط به دو تابع   purchaseFailed و notVerified جابه جا گذ اشته شده است 
[
![Screenshot from 2021-11-08 13-26-59](https://user-images.githubusercontent.com/42632697/140722634-1300c912-4eb2-45a3-80f0-9a9f0b88726b.png)
![Screenshot from 2021-11-08 13-23-48](https://user-images.githubusercontent.com/42632697/140722660-fe3230ad-95eb-4050-81f0-f8e4ddddd3dc.png)
](url)

**Comment by khanzadimahdi** [comment]
دوست عزیز فیکس کنید و درخواست مرج بزارید
