### ISSUE TITLE
انتخاب درگاه در زرین پال

### ISSUE THREAD

**Issue by miladbrave** [shetabit/multipay#116]
سلام وقت بخییر
من می خواستم در درایور زرین پال به آخر لینک پرداخت رشته ای اضافه کنم تا در هنگام وصل شدن به درگاه به صورت راندم بانک انتخاب نکنه(مثلا در لینک زیر مستقیم به به پرداخت وصل میشه)
https://normal.zarinpal.com/pg/StartPay/0000000000000000000000000000000001/bpm
این قابلیت در پکیج هست؟
تشکر

**Comment by khanzadimahdi** [comment]
دیتا مربوط به پرداخت رو درون دیتابیس قرار بدید بعدش توی ادرس برگشت دیتا رو لود کنید استفاده کنید

/payment/123

مثلا توی  ادرس بالا 123 رو بگیرید و رکورد مربوط بهش رو از دیتابیس بکشید بیرون و باقی ماجرا

**Comment by miladbrave** [comment]
اگه منظورتون از دیتای برگشت همون دیتای بزرگردانده شده از درگاه هست که اون اصلا به درد نمیخوره.. چون من میخوام قبل انتقال به درگاه متغییرمو اضافه کنم
درضمن این مقدار میتوان از طریق متد purchase و وندور بدم ولی این روش درست نیست!
