### ISSUE TITLE
مشکل در پی پینگ

### ISSUE THREAD

**Issue by AliGh1** [shetabit/multipay#13]
سلام 
`$transactionId`
 رو داخل دیتابیس نگه میدارم اما با 
`clientrefid`
برگشت داده شده یکی نیست
حتی کلاس 
`PAYPING`
رو هم که نگاه کردم 
`"clientRefId" => $this->invoice->getUuid(),`
به این صورت پیاده سازی شده و در واقع
`$this->invoice->getUuid()`
رو به عنوان 
`clientrefid`
برمیگردونه
!!!

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
باید بگم که clientrefid یک توکن یا مقدار یونیک هست و ما اون رو به عنوان شناسه ی پرداخت به پی پینگ میدیم تا بعد از پرداخت بتونیم دوباره با همون شناسه پرداخت خودمون رو پیگیری کنیم

شماره تراکنش چیزی هست که پی پینگ به ما میده. ما یک صورتحساب ثبت میکنیم و پی پینگ کد تراکنش رو به ما میده. حالا با استفاه از اون کد تراکنش میتونیم تراکنش رو انجام بدیم (منظور از تراکنش پرداخت هست در اینجا) اگه فکر میکنید جایی مشکل داره اون رو  فیکس کنید و در خواست مرج بدید تا بررسی کنیم باهم و مشکل رو رفع کنیم. من به شخصه فکر نمیکنم مشکلی وجود داشته باشه

</div>
