### ISSUE TITLE
تبدیل نکردن قیمت نهایی به ریال در برخی از درایورها

### ISSUE THREAD

**Issue by tohidnateghi** [shetabit/multipay#134]
سلام وقت بخیر ممنون بابت پکیج خیلی خوبتون،
یه مشکلی که هست توی بعضی از درایورها مثل درایور درگاه idpay قیمت نهایی ضربدر 10 نشده و همون عدد رو به درگاه میفرسته، درحالی که توی برخی درایورها مثل به پرداخت و  payir و  زرین پال عدد نهایی که به درگاه پرداخت ارسال میشه ضربدر  10 میشه

لطفا بررسی کنید، تشکر

**Comment by tohidnateghi** [comment]
اگه خواستید من میتونم یکی یکی درایور ها رو بررسی کنم و تو هر کدوم که ضربدر 10 نشه اعمال کنم

**Comment by khanzadimahdi** [comment]
اگه اینکار رو انجام بدید ممنون میشم. اما دقت کنید عدد واقعی رو باید بعد از به درگاه رفتن چک کنید. بعضی درایور ها ریال قبول میکنن و باید تقسیم بر 10 بشن.

**Comment by khanzadimahdi** [comment]
I close this issue due to inactivity.
