### ISSUE TITLE
درایور jibit

### ISSUE THREAD

**Issue by MiladBackDev** [shetabit/multipay#138]
سلام
برای Jibit درایوری نوشته شده؟اگه آره کیrelease میشه؟

**Comment by khanzadimahdi** [comment]
سلام دوست عزیز. در حال حاضر درایور jibit موجود نیست. اگه امکانش هست اضافه کنید و درخواست مرج بزارید.

**Comment by ixabolfazl** [comment]
@aryala7 


سلام

[مستندات درگاه پرداخت](https://napi.jibit.ir/ppg/v3/static/docs/index.html)

[نمونه کد برای php ](https://newdashboard.jibit.ir/assets/documents/Jibit-class-v3.zip)

[مستندات تسویه حساب](https://newdashboard.jibit.ir/assets/documents/220209-Jibit-Transferor_REST_API_Documentation_(V2.1).pdf)

[مستندات سرویس استعلام ](https://newdashboard.jibit.ir/assets/documents/Jibit-Identicator_Project_(V1.4.5)-Tech-Persian.pdf)

**Comment by aryala7** [comment]
@ixabolfazl سلام
مرسی اضافش میکنم

**Comment by j3yzz** [comment]
سلام

من هرچی سایت رو بالا پایین کردم ندیدم api key تست داشته باشه
اگر اطلاع دارین لطف کنید بگید تا این درگاه رو اضافه کنم مرسی

**Comment by shdehnavi** [comment]
#218
Jibit driver has been added.
