### ISSUE TITLE
درگاه وندار

### ISSUE THREAD

**Issue by masoudabdan** [shetabit/multipay#139]
سلام. امکان افزودن درگاه وندار به این پکیج براتون مقدور هست؟

**Comment by khanzadimahdi** [comment]
سلام وقتتون بخیر. درگاه رو اضافه کنید درخواست مرج بزارید. پکیج به صورت اوپن سورس داره توسعه پیدا میکنه.

**Comment by khanzadimahdi** [comment]
https://github.com/shetabit/multipay/pull/144
