### ISSUE TITLE
بروزرسانی درگاه pay.ir با توجه به مستندات جدید (ورژن جدید)

### ISSUE THREAD

**Issue by sina-developer** [shetabit/multipay#14]
سلام و خسته نباشید

بعد از قطع اتصال سراسری 

pay.ir

 و ارتقاء سیستمش ظاهرا کد های شما با آپدیت جدید درگاه دچار مشکل شده

سایتی که قبلا با همین پکیج پیاده سازی شده بود، خود به خود با خطا مواجه میشه

متن خطا :

cURL error 7: Failed to connect to pay.ir port 80: No route to host (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

در ضمن از لاراول نسخه 7 استفاده میکنم

متشکرم

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
سلام میتونید مشکل رو رفع کنید و درخواست مرج شدن بدید؟ کدها رو میتونید در مسیر زیر پیدا کنید
</div>

```html
vendor/shetabit/multipay/src/Drivers/Payir/Payir.php
```

https://github.com/shetabit/multipay/blob/master/src/Drivers/Payir/Payir.php

**Comment by sina-developer** [comment]
> سلام میتونید مشکل رو رفع کنید و درخواست مرج شدن بدید؟ کدها رو میتونید در مسیر زیر پیدا کنید
> ```
> vendor/shetabit/multipay/src/Drivers/Payir/Payir.php
> ```
> 
> https://github.com/shetabit/multipay/blob/master/src/Drivers/Payir/Payir.php

بسیار خب!

مشکل حل شد

راه حلش هم استفاده از آدرس زیر : 

https://pay.ir/pg/send

به جای 

https://pay.ir/pg/send/

در کانفیگ مخصوص پی آی آر مقدار 

apiPurchaseUrl

میدونم، خیلی باگ عجیبی بود!

**Comment by khanzadimahdi** [comment]
میتونید باگ رو فیکس کنید؟ تنظیمات توی ادرس زیر هست

https://github.com/shetabit/multipay/blob/master/config/payment.php

رپازیتوری رو فورک کنید و تغییرات رو اعمال کنید و درخواست مرج بدید

**Comment by sina-developer** [comment]
> میتونید باگ رو فیکس کنید؟ تنظیمات توی ادرس زیر هست
> 
> https://github.com/shetabit/multipay/blob/master/config/payment.php
> 
> رپازیتوری رو فورک کنید و تغییرات رو اعمال کنید و درخواست مرج بدید

تغییرات اعمال شد، میتونید مرج کنید

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
دقیقا کجا اعمال شد؟ pull request بدید
</div>

**Comment by sina-developer** [comment]
> دقیقا کجا اعمال شد؟ pull request بدید

همین فایل 

https://github.com/shetabit/multipay/blob/master/config/payment.php

درخواست ارسال شد
