### ISSUE TITLE
درگاه جدید کشاورزی و صادرات بر پایه پرداخت الکترونیک سامان

### ISSUE THREAD

**Issue by hsharghi** [shetabit/multipay#167]
جدیدا درگاه بانک کشاورزی و صادرات هر دو داکیومنت مربوط به پرداخت الکترونیک سامان رو ارسال میکنن برای توسعه دهنده ها. که کمی با درگاه فعلی سامان متفاوت هست. 
میخواستم ببینم برای اضافه کردن این دو بانک دو درایور مجزا به اسم های Keshavarzi و Saderat بسازم یا کلا یه درایور به نام SEP (Saman Electronic Payment) بسازم  و pull request بدم؟

**Comment by khanzadimahdi** [comment]
بله. ممنونم.
