### ISSUE TITLE
درگاه های پرداخت که میشه اضافه کرده تا تکمیل ترین پکیج پرداختی بشه

### ISSUE THREAD

**Issue by pichanak** [shetabit/multipay#169]
اولا ممنون بابت این پکیج خیلی خوبتون و امیدوارم همیشه موفق باشین و اینکه پیشنهاد میکنم که اگر به مستندات این درگاه ها هم دسترسی داشتین اضافه کنید عالی میشه.

درگاه پرداخت زیر :

1. درگاه بانک قوامین
2. درگاه بانک اقتصاد نوین
3. درگاه بانک کشاورزی
4.  درگاه پست بانک
5. درگاه بانک صادرات
6. درگاه بانک تجارت
7. درگاه واسط Jibit
8. درگاه واسط Bahamta
9. درگاه واسط سامان کیش
10. درگاه واسط APSAN (تالی)
11. درگاه واسط سایان
12. درگاه واسط پی‌فا
13. درگاه تارا
14. درگاه نوینو
15. درگاه پرداخت اقساطی اسنپ پی
16. درگاه پرداخت ایران کیش جدید (اونی که تو پکیج هست ایران کیش قدیم هست)
17.  درگاه واسط پارس پال (که حتی از زرین پال هم قدیمتر بوده ولی چون دامنه شو چند مدت فیلتر کردن و مجبور شد اسم آرین پال و کار کنه و الان هر دو سایت مال یه شرکته)

درگاه پرداخت paypal و credit card هارو هم اگه بتونید بزارید عالی میشه اینجوری سایت های چند زبانه وقتی پیاده سازی میکنیم دیگه راحت میشیم

سپاس

**Comment by khanzadimahdi** [comment]
با سلام. پکیج اوپن سورس هست و شما خودتون نیز میتونید هر درگاهی رو به پکیج اضافه کنید و درخواست مرج بدید.
