### ISSUE TITLE
برگشت ناموفق در بانک ملت

### ISSUE THREAD

**Issue by mvc0** [shetabit/multipay#171]
```
The POST method is not supported for this route. Supported methods: GET, HEAD.
```

این خطایی که در هنگام استفاده از درگاه بانک ملت هست.
دوتا درایو زرینپال و پاسارگاد به خوبی کار میکنن ***کامل تست کردم***
**هر چند واسه پاسارگاد باید دستی به ``تومان`` تبدیلش کنیم**
ولی بانک ملت این خطا رو میده چیکار کنم؟ممنون از راهنمایی

**Comment by alissn** [comment]
@mvc0 
مشکل از تعریف Route شماست.

روت وریفایتون فقط متد `get` قبول می کنه. باید متد `post` هم بهش اضافه کنید.
```php
Route::match(['get','post'],'verify', [PayController::class, 'verify'])->name('verify');
```
