### ISSUE TITLE
تبدیل مبلغ به ریال در درایور آسان پرداخت

### ISSUE THREAD

**Issue by Mohammadreza-73** [shetabit/multipay#180]
سلام
من مبالغ رو خودم در پروژه به ریال مدیریت می کنم، در درایور آسان پرداخت میاد و مبلغ رو در 10 ضرب میکنه!
بهتر نیس که مثل درایور atipay مقدار currency (Can be R, T (Rial, Toman)) رو هم در فایل کانفیگ مشخص کنیم؟

[آسان پرداخت](https://github.com/shetabit/multipay/blob/cdf32a45ce4d24943046699a4e72e2cdebd054ab/src/Drivers/Asanpardakht/Asanpardakht.php#L64)

**Comment by parsariyahi** [comment]
برو انجام بده. مرسی اه.

**Comment by khanzadimahdi** [comment]
دوست عزیز بله کاملا درسته. یکسری از درگاه ها بای دیفالت ریال و یکسری تومان هستن. در این پکیج تمامی درگاه ها با تومان کار میکنن و ما هرجایی که ریال بوده رو در عدد ۱۰ ضرب کردیم.

**Comment by khanzadimahdi** [comment]
@parsariyahi بامزه بود. موفق باشید
