### ISSUE TITLE
نداشتن password توی درگاه سامان

### ISSUE THREAD

**Issue by mohammad5525** [shetabit/multipay#19]
توی فایل کانفیگ درگاه توی بخش سامان باید دو تا ورودی دریافت کنه:
1- مرچند ایدی merchantId
2- پسورد password

در صورتی که الان فقط داره مرچند ایدی رو ورودی میگیره . ورودی پسورد نیست

**Comment by khanzadimahdi** [comment]
سلام. مثل اینکه به پسوورد نیازی نیست. میتونید کدهای درایور سامان رو از مسیر زیر ببینید

https://github.com/shetabit/multipay/blob/master/src/Drivers/Saman/Saman.php

درگاه تست شده و باید درست کار کنه. به هر حال اگه باگ یا فیچر جدیدی مد نظر هست اون رو اظافه کنید و درخواست مرج شدن بدید تا به پکیج اظافه بشه
