### ISSUE TITLE
واحد قیمت در هر درایور

### ISSUE THREAD

**Issue by vahidkaargar** [shetabit/multipay#193]
سلام

بنده در دو درایور نکست پی و پی استار متوجه شدم اولی قیمت را به تومان و دومی به ریال دریافت میکند. برای موضوع واحد مبلغ چه فکری شده؟ شما در نظر بگیرید در آینده قرار است درگاه های ارزی هم اضافه کنید.
در واقع بنظر میاد بعضی از درگاه ها در کانفیگ, نوع ارز رو مشخص کرده اند اما نوع ارز را باید سایت مشخص کند و نه هر درایور بصورت جداگانه

بنظر جای این متد خالی هست:
```php
(new Invoice)->amount(1000)->currency('IRR'); // IRR, IRT, USD, EUR, ...
```

ممنون میشم توضیحاتی ارایه بدهید

**Comment by vahidalvandi** [comment]
این ویژگی موجود نیست ولی بودنش خیلی خوبه که منم موافق اضافه شدن هستم حداقل برای ریال و تومان

**Comment by khanzadimahdi** [comment]
it can be implemented like this: https://github.com/shetabit/multipay/pull/195

**Comment by khanzadimahdi** [comment]
could you please implement it and send a PR ?
