### ISSUE TITLE
خطای بازگشت وجهه در درگاه پارسیان

### ISSUE THREAD

**Issue by amousavii** [shetabit/multipay#20]
<div dir="rtl">
با سلام
متاسفانه بعد از ریدایرکت به صفحه درگاه بانک پارسیان با خطای زیر مواجه میشم:

_مشتري گرامی با عنایت به اینکه تأییـدیه تراکنش شـما نیاز به سپري شـدن 60 دقیقه دارد،چنانچه مبلغ تراکنش ازحساب شـما کسـرشده و خدماتی دریافت نکردید لطفا پس از سپري شدن 60 دقیقه از زمان تراکنش، گردش حساب خود را بررسـی و درصورتی که مبلغ عودت نگردیده بود، با پشتیبانی مرکز تماس 2318تماس حاصل فرمائید_

کد های انتقال به درگاه بانک من :
</div>

```php
$invoice = (new Invoice)->amount(1000);
return Payment1::callbackUrl('https://xyz.com/parsianResult')->via('parsian')->purchase($invoice, function ($driver, $transactionId) {
//My Order Create
})->pay()->render();
```
<div dir="rtl">
ممنون میشم اگر دوستان همچین مشکلی برخوردند راهنمایی کنن
</div>

![Screenshot_20200905_133143](https://user-images.githubusercontent.com/43773690/92301998-aff15280-ef7d-11ea-8755-3aa1e820f15f.png)

**Comment by amousavii** [comment]
طبق مستندات جدید آدرس انتقال به درگاه باید به همراه توکن باشه .
برای همین تو فایل درایور پارسیان باید خط 83 اصلاح بشه مثل نمونه زیر:
   $payUrl = $this->settings->apiPaymentUrl . '?Token=' . $this->invoice->getTransactionId() ;
این رو گذاشتم تا اگر کسی مثل من مشکل داشت بتونه حلش کنه

**Comment by khanzadimahdi** [comment]
لطفا پکیج رو فورک کنید و مشکل رو داخل پکیج رفع کنید و درخواست مرج بدید
