### ISSUE TITLE
release tag issue

### ISSUE THREAD

**Issue by ariaieboy** [shetabit/multipay#201]
سلام آخرین ریلیز که انجام شده اشتباه تگ شده و به همین خاطر آپدیت روی کامپوزر قرار نگرفته لطفا این مورد را اصلاح کنید.
https://github.com/shetabit/multipay/releases/tag/v.133.0
@khanzadimahdi

**Comment by khanzadimahdi** [comment]
https://github.com/shetabit/multipay/releases/tag/v1.33.0
