### ISSUE TITLE
New release, doesn't support PHP 8+

### ISSUE THREAD

**Issue by bahramsadin** [shetabit/multipay#222]
@khanzadimahdi 
پکیج "chillerlan/php-cache": "4.0", که در این pr اضافه شده از php7.4 فقط پشتیبانی و در نتیجه امکان آپدیت پروژه هایی که با php8 یا بالاتر نوشته شده به این ورژن جدید نیست
در کل هم فکر نمیکنم کلا پکیج جالبی باشه و اگه از یه پکیج جایگزین استفاده بشه بهتره چون ورژن آخرش هم مثلا فقط از ^7.4 || ^8.0 استفاده میکنه باز نسخه های بالاتر به مشکل میخورن....

![Screenshot 2024-01-29 221954](https://github.com/shetabit/multipay/assets/24217539/b6a5cafa-e543-423e-90a2-fbb6417a3606)

_Originally posted by @bahramsadin in https://github.com/shetabit/multipay/issues/218#issuecomment-1915357534_

**Comment by khanzadimahdi** [comment]
وقت بخیر. میتونید لطفا پکیج بهتری معرفی کنید؟ نشانه گذاری به صورت ^8.0 یعنی از تمام ورژن های 8 تا قبل 9 پشتیبانی میشه.

**Comment by khanzadimahdi** [comment]
@shdehnavi what do you think about this? =)

**Comment by shdehnavi** [comment]
I haven't had the opportunity to work with a similar package before. The chillerlan/php-cache package, last updated on April 18, 2021, supports PHP 8.1:
[Check it out here!](https://github.com/chillerlan/php-cache/releases/tag/4.1.0)

**Comment by khanzadimahdi** [comment]
I had a look at the packages that implement php-fig cache PSR. I believe we can use https://github.com/PHPSocialNetwork/phpfastcache

**Comment by khanzadimahdi** [comment]
also asked https://github.com/chillerlan/php-cache/issues/3 about supporting PHP8.1+

**Comment by codemasher** [comment]
Hi, I see you have a bogus requirement for that library in your `composer.json`, which does not allow for minor version updates:
https://github.com/shetabit/multipay/blob/7a76b04cf7ea12876d8e5990bebc29545d208ad2/composer.json#L88
The library supports PHP8 [from version 4.1 on](https://packagist.org/packages/chillerlan/php-cache#4.1.0) - you should change the requirement to `^4.1`. The version in the main branch will only support PHP > 8.1.

**Comment by khanzadimahdi** [comment]
fixed in https://github.com/shetabit/multipay/releases/tag/v1.43.0
