### ISSUE TITLE
پرداخت پوز سپ

### ISSUE THREAD

**Issue by sajadshouli** [shetabit/multipay#224]
از اونجایی که توی پروژه ها پیش میاد که علاوه بر درگاه پرداخت با پوز هم داشته باشیم میخواستم بدونم درایور سپ اینکارو می کنه یا نیازه پیاده سازی بشه
و اینکه من میتونم برای پرداخت با پوز سپ مرج ریکوست بفرسته که اضافه بشه

**Comment by khanzadimahdi** [comment]
سلام وقت بخیر. من دقیقا نمیدونم که با پوز هم میشه اینکار رو کرد یا نه! اما به هر حال میتونید کد سپ رو توی ادرس زیر پیدا کنید. همچنین اگه فیچری که میخواید نبود میتونید مرج رکوئست بفرستید:

https://github.com/shetabit/multipay/tree/master/src/Drivers/SEP
