### ISSUE TITLE
خطای درگاه جیبیت

### ISSUE THREAD

**Issue by mirbaagheri** [shetabit/multipay#232]
به هنگام استفاده از درگاه `جیبیت` با ارور زیر مواجه میشیم:
`"Undefined property: stdClass::$apiSecret"`
متوجه شدم در فایل `config/payment.php` کلید `secretKey` رو باید به `apiSecret` تغییر بدم.
یعنی یک مقدار دهی اشتباه در اینجا صورت گرفته که نیاز به اصلاح داره.

**Comment by khanzadimahdi** [comment]
fixed on the new release.
