### ISSUE TITLE
مشکل در ثبت تراکنش 

### ISSUE THREAD

**Issue by aminmohammadmazreali** [shetabit/multipay#24]
سلام 

بعضی وقت ها وقتی فانکشن رو کال میکنم داخلش نمیره و ازش رد میشه و  دیتایی داخل دیتابیس ثبت نمیشه که وقتی از درگاه برمیگرده بتونیم پیگیری کنیم.

```
Payment::callbackUrl(route('payment.verify'))->purchase(
            (new Invoice)->amount(10000)
                ->via($payment_gateway),
            function ($driver, $transaction_id){
//داخل این بخش نمیشه بعضی وقت ها
// و چون داخل این قسمت نمیشه نمیتونم تو دیتابیس ذخیره کنم
                $invoice = $driver->getInvoice();
                $description = [
                    'transaction_id' => $transaction_id,
                    'uuid' => $invoice->getUuid(),
                ];
            }
        )->pay()->render();
```

نمیدونم مشکلش چیه! داره کار میکنه مثلا 119هزارتا تراکنش داریم الان 100 تاش اینجوری شده

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
امکان نداره چنین اتفاقی بیوفته
میتونید خط 212 از فایل زیر رو ببینید

</div>

https://github.com/shetabit/multipay/blob/master/src/Payment.php#L213

**Comment by khanzadimahdi** [comment]
درصوتی که حس میکنید خطایی وجود داره اون رو رفع کنید و درخواست مرج شدن بدید
