### ISSUE TITLE
مشکل وریفای در درگاه پارسیان که همیشه ارور کنسلی کاربر را میده

### ISSUE THREAD

**Issue by MohammadGhorayshi** [shetabit/multipay#243]
سلام وقت بخیر وقتی میخوایم از این پکیج به عنوان API استفاده کنیم و مستقیم به کال بک بانک متصل نکنیم این مشکل بوجود میاد که جزییات بیشتر را براتون میفرستم
ریسپانسی که همیشه میده: انصراف کاربر هست
دلیل این ریسپانس هم این قطعه کده که باعث میشه همیشه ارور نمایش بده وقتی این قطعه کد را کامنت میکنم درست میشه:
توی مسیر زیر:
`vendor/shetabit/multipay/src/Drivers/Parsian`

توی متد `verify`
```
$status = Request::input('status');
$token = Request::input('Token');
if ($status != 0 || empty($token)) {
    throw new InvalidPaymentException('تراکنش توسط کاربر کنسل شده است.');
}
```
توی مستندات جایی ذکر نشده که چجوری token و status را بفرستیم برای همین همیشه توی کال بک ارور کنسلی نمایش میده

`Payment::via('parsian')->config('merchantId', $merchantId)->amount($amount)->transactionId($transaction_id)->verify();`

**Comment by MohammadGhorayshi** [comment]
راه حلش هم فکر کنم توی متد `prepareVerificationData` انجام دادی یعنی یا از `Request` بخونه یا از کانفیگ بخونه:

`$transactionId = $this->invoice->getTransactionId() ?? Request::input('Token');`

اگه این خط را به ریپو اضافه کنی، من کارم راه میفته یعنی خط 103 را یه ویرایش ریز انجام بدی:

`$token = $this->invoice->getTransactionId() ?? Request::input('Token');`

اگر راه حل دیگه ایی داره خوشحال میشم برام بنویسی

@khanzadimahdi

**Comment by khanzadimahdi** [comment]
وقت بخیر.
یک سوال برام پیش اومده! چرا کال بک بانک رو به اندپوینت مورد نظرتون وصل نکردین؟
شما میتونید شماره تراکنش رو یه جا ذخیره کنید و بعد ایدیشو توی ادرس کالبک استفاده کنید مثلا
```
/path/to/123/payment
```

وقتی بانک به ادرس بالا برمیگرده شما اون 123 رو از دیتابیس میخونید و دیتای مورد نظرتون واسه وریفای کردن پرداخت رو لود میکنید.

**Comment by MohammadGhorayshi** [comment]
خب دلیلش خیلی طولانیه ولی من یه سیستم فروشگاه ساز پیاده کردم و کلا فرانت من با Next.js نوشته شده و اگه بخوام مستقیم این قسمت بیارم اصلا وریفای نیست و داستان های این چنینی دارم.
این راه حلی که گفتم مشکلی بوجود میاره؟
یا اگر راه حل دیگه ایی داره خوشحال میشم بهم بگی که چجوری این دیتا را بفرستم؟
من از سمت فرانت دارم شماره تراکنش را برای اندپوینتم میفرستم و وریفای بر اساس شماره تراکنش انجام میشه
کدی هم که برای وریفای دارم به اینصورت هست:

`Payment::via('parsian')->config('merchantId', $merchantId)->amount($amount)->transactionId($transaction_id)->verify();`

اگر میشه توی این دستور `token`را ست کرد خب انجام بدم ولی چون نمیشه توکن را از اینجا تنظیم کرد و توی شرط میره، همیشه بهم ارور میده که کاربر کنسل کرده درحالیکه این ارور درست نیست.

```
$status = Request::input('status');
$token = Request::input('Token');
if ($status != 0 || empty($token)) {
    throw new InvalidPaymentException('تراکنش توسط کاربر کنسل شده است.');
}
```
توی این شرط نه `token` و نه `status` ست نشده. به نظرم این کد را اضافه کنی مشکلی توی کار سیستم بوجود نمیاد و برای ماهایی که داریم از چند درگاه همزمان برای چند تا سایت استفاده میکنیم راحت تر میشه
ممنونم

**Comment by MohammadGhorayshi** [comment]
سلام وقت بخیر
این مورد که بهش اشاره کردم را اضافه نمیکنی؟ تا الان کسی به چنین اروری نخورده؟
@khanzadimahdi

**Comment by MohammadGhorayshi** [comment]
واقعا؟؟؟
خب الان من چطوری باید از پکیج استفاده کنم؟ الان توکن چجوری برای متد وریفای بفرستم؟

`Request::input('Token')`

شما داری این قطعه کد را فراخوانی میکنی و میگی اگه توکن نداشتیم ارور بده، جایی هم توی داکیومنت ذکر نکردی که چجوری توکن را بفرستیم.
روش پیاده سازی مگه توی نوشتن کتابخونه مهمه؟ کجای دنیا روش پیاده سازی را کسی که کتابخونه نوشته مشخص میکنه؟ شما متدها را تعریف میکنی و بقیه بر اساس معماری سیستم خودشون استفاده میکنن، منظقه شما مثل این هست که بانک پارسیان بگه حتما کال بک هاتون باید توی فلان مسیر خاص باشه و اگر مسیره دیگه یا معماری دیگه تعریف کنین دیگه نمیتونین به درگاه پارسیان متصل بشین.
شما میگی کال بک مستقیم بانک را به کتابخونه شما باید متصل کنیم تا این مشکل بوجود نیاد، واقعا این منطقیه؟ این چه منطقیه که منه برنامه نویس باید کال بک مستقیم بانک را به هسته ی اصلی برنامه ی خودم متصل کنم؟ این بین من یه سری درخواست را فیلتر میکنم و وریفای میکنم و بعد از دو تا درخواست به هسته ی اصلی برنامه میرسم.
من فرانت را با نکست پیاده سازی کردم و این وسط بین فرانت و بک با `GraphQL` اتصال برقرار میکنم. الان شما به من بگو اگه من دارم اینطوری استفاده میکنم یعنی نمیتونم از پکیج شما استفاده کنم؟
شما یه نمونه از روش پیاده سازی اینکه اگر فرانت با ریکت یا نکست باشه و ارتباط با گرف یا رست باشه را برای بانک پارسیان بزار تا افرادی که مثل من از دانش کافی برخوردار نیستن بتونن استفاده کنن. یه تجدید نظر نسبت به پکیجت داشته باش تا همه بتونن از پکیج استفاده کنن نه اینکه فقط یه عده ی خاص با معماری خاص بتونن استفاده کنن.
برام جالبه کل تغییری که میخوای اعمال کنی در حد ۲۰ تا کلمه هم نیست و جالب تر هم اینه که اگه داری از ریکویست، ترنزکشن را میخونی، پس چرا پایین تر داری میگی اگر کاربر ست نکرد از ریکویست بخون این فانکشن هم خودتون نوشتین و اگر مشکلی وجود داره پس دلیلی نداره که اینجا هم از این خط استفاده کنین.
این متدی هست که توی پکیج دارین ازش استفاده میکنین (یا شما اصلا به ایشو دقت نکردین و جواب سر بالا دادین یا این خط کد هم توی پکیجتون باید حذف بشه):
```
    protected function prepareVerificationData()
    {
        $transactionId = $this->invoice->getTransactionId() ?? Request::input('Token');

        return array(
            'LoginAccount'      => $this->settings->merchantId,
            'Token'         => $transactionId,
        );
    }
```


اصلا فکر نمیکردم همچین رفتار غیرحرفه ایی از سمت شما باشه.

**Comment by khanzadimahdi** [comment]
دوست عزیر روش کار به این صورت هست که بانک به ادرسی که شما بهش دادین ریدایرکت میکنه. این ریدایرکت یا به صورت GET انجام میشه یا POST که در هر دو حالت شما میتونید محتوایی که بانک ارسال کرده رو به راحتی دریافت کنید.
مشکل شما اینه که کدی که برای فرانت در نظرگرفتین این محتوا رو برای بکند ارسال نمیکنه. مشکل رو سمت خودتون باید حل کنید نه اینکه پکیج رو به خاطر یوزکیس شما عوض کنیم!
روش دوم اینه که شما درایور مورد نظر خودتون رو با کدی که مد نظرتون هست بسازید و اون رو توی فایل config.php معرفی کنید وهر کدی که دوسدارید میتونید توی درایوری که ساختید بنویسید بر حسب نیازی که دارید. دقت کنید توی config.php میتونید لیست درایور ها و کانفیگ هاشون رو معرفی کنید.

لطفا بحث رو به حاشیه نکشید و روی حل شدن مشکلتون فوکوس کنید.

**Comment by khanzadimahdi** [comment]
من کد رو دوباره چک کردم و باهاتون موافق هستم که باید تغییرااتی انجام بشه

https://github.com/shetabit/multipay/blob/master/src/Drivers/Parsian/Parsian.php#L153

خط بالا باید مطابق زیر تغییر بکنه

```php
        $transactionId = $this->invoice->getTransactionId() ?? Request::input('Token');
```

میشه لطفا PR  بزارید براش؟ ممنونم.

**Comment by MohammadGhorayshi** [comment]
دقیقا موافقم یعنی اگر این خط کد را اضافه کنیم و status هم بررسی نکنیم مشکلی توی روند اصلی بوجود نمیاره و این خطا هم برطرف میشه.

ممنونم ازت که یک بار دیگه کد را بررسی کردی، من یه درایو دیگه درست کردم ولی خب خواستم این مشکل برای بقیه دوستان و همکاران بوجود نیاد.

من امروز یه pull request میفرستم.
