### ISSUE TITLE
Timeout handling

### ISSUE THREAD

**Issue by fromseer** [shetabit/multipay#245]
امروز زرین پال برای لحظاتی ایران اکسس شده بود:

```
cURL error 28: Failed to connect to api.zarinpal.com port 443 after 129436 ms: Couldn't connect to server
```

من یک نگاهی به کدبیس انداختم ولی هیچ چیزی در رابطه تعیین میزان تایم اوت برقراری سرور برای گازل ندیدم همینجور تو ارور بالا که میبینید 120 ثانیه کلاینت منتظر مونده ولی من میخوام نهایت 10 ثانیه که خودم هندلش کنم، 

اومدم pr بفرستم ولی متاسفانه با ساختار اشناییت ندارم که جوری اکی کنم برای باقی درایورها هم اکی بشه

**Comment by khanzadimahdi** [comment]
سلام. واسه هر درایور باید به صورت جداگانه تنظیم کرد.
