### ISSUE TITLE
خطای SOAP-ERROR

### ISSUE THREAD

**Issue by sanaz1992** [shetabit/multipay#276]
سلام 
چند هفته است درگاه تست زرین پال این خطا رو میده
SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://sandbox.zarinpal.com/pg/services/WebGate/wsdl' : failed to load external entity "https://sandbox.zarinpal.com/pg/services/WebGate/wsdl"

میشه راهنمایی کنید لطفا

**Comment by khanzadimahdi** [comment]
سلام وقت بخیر. این ادرس سند باکس هست و اگه خطایی باشه از سمت زرین پال باید باشه و مربوط به پکیج نمیشه. لطفا این مشکل رو با زرین پال مطرح کنید.

**Comment by mohaphez** [comment]
Hello everyone,

According to the official [documentation](https://next.zarinpal.com/paymentGateway/sandbox.html), SOAP web services have been deprecated and replaced with REST APIs. Merging PR #277 will resolve this issue.

Thanks in advance !

**Comment by khanzadimahdi** [comment]
Thanks @mohaphez , I merged the PR and released [v1.56.0](https://github.com/shetabit/multipay/releases/tag/v1.56.0)

@sanaz1992 please update your package, this issue is fixed in the new release (v1.56.0)
