### ISSUE TITLE
دریافت اطلاعات مازاد

### ISSUE THREAD

**Issue by alireza-hnzpv** [shetabit/multipay#286]
سلام وقت بخیر،
برای اینکه کد پیگیری تراکنش و شماره کارت مشتری رو از $receipt بگیرم، باید از چه متغیری استفاده کنم که بین تمامی درایور ها یکسان باشه؟
میخوام ببینم اسم مشترکی بین درگاه ها داره یا نه؟
حالا اگه درگاهی هم نداد مهم نیست ولی میخوام اگه درگاهی میده این مشخصات رو حتما من داشته باشمش

**Comment by khanzadimahdi** [comment]
برای دریافت شماره کارت مشتری راه یکسانی بین درگاه ها وجود نداره. اما برای شماره تراکنش میتونید از `getReferenceId` استفاده کنید.

https://github.com/shetabit/multipay/blob/master/src/Abstracts/Receipt.php#L60

از متد getDetails هم میتونید تمامی اطلاعاتی ک توی رسید هست رو دریافت و ذخیره کنید.
