### ISSUE TITLE
مشکل در وریفای کردن پرداخت های درگاه ایرانکیش

### ISSUE THREAD

**Issue by jalallinux** [shetabit/multipay#35]
```php
    public function verify() : ReceiptInterface
    {
        $data = array(
            'merchantId' => $this->settings->merchantId,
            'sha1Key' => $this->settings->sha1Key,
            'token' => $this->invoice->getTransactionId(),
            'amount' => $this->invoice->getAmount() * 10, // convert to rial
            - 'referenceNumber' => Request::get('referenceId'),              <--- invalid line
            + 'referenceNumber' => Request::post('referenceId'),           <--- correct line
        );

        $soap = new \SoapClient($this->settings->apiVerificationUrl);
        $response = $soap->KicccPaymentsVerification($data);

        $status = (int) ($response->KicccPaymentsVerificationResult);

        if ($status != $data['amount']) {
            $this->notVerified($status);
        }

        return $this->createReceipt($data['referenceNumber']);
    }
```

سلام شما توی وریفای درگاه ایرانکیش کال بک این درگاه رو گت در نظر گرفتی در صورتی که توی داکیومنتای ایران کیش که چندینننن ساله تکون نخورده گفته کالبکشون پست میشه.

بعد چطور شما میگی این درگاه ها تست شده من نمیدونم؟
لطفا این موضوع رو بررسی کنید و درصورت امکان این مشکل رو فیکس کنید.
ممنونم

_Originally posted by @jalallinux in https://github.com/shetabit/payment/issues/126#issuecomment-745332021_

**Comment by jalallinux** [comment]
@khanzadimahdi انجام شد.
ممنونم از پیگیریتون

**Comment by jalallinux** [comment]
ی سوال دیگه برام پیش اومده روی همین درایور ایرانکیش

چطور میتونم وقتی کالبک بانک میاد به روتی که تعریف کردم بفهمم نتیجه چی بوده؟ منظورم موفق و ناموفق نیستا منظورم مسیج های بانکه که شما فقط برای برسی ریزالت وریفای گذاشتی.

‍‍‍```
private function notVerified($status)
    {
        $translations = array(
            110 => 'دارنده کارت انصراف داده است',
            120 => 'موجودی حساب کافی نمی باشد',
            121 => 'مبلغ تراکنشهای کارت بیش از حد مجاز است',
            130 => 'اطلاعات کارت نادرست می باشد',
            131 => 'رمز کارت اشتباه است',
            132 => 'کارت مسدود است',
            133 => 'کارت منقضی شده است',
            140 => 'زمان مورد نظر به پایان رسیده است',
            150 => 'خطای داخلی بانک به وجود آمده است',
            160 => 'خطای انقضای کارت به وجود امده یا اطلاعات CVV2 اشتباه است',
            166 => 'بانک صادر کننده کارت شما مجوز انجام تراکنش را صادر نکرده است',
            167 => 'خطا در مبلغ تراکنش',
            200 => 'مبلغ تراکنش بیش از حدنصاب مجاز',
            201 => 'مبلغ تراکنش بیش از حدنصاب مجاز برای روز کاری',
            202 => 'مبلغ تراکنش بیش از حدنصاب مجاز برای ماه کاری',
            203 => 'تعداد تراکنشهای مجاز از حد نصاب گذشته است',
            499 => 'خطای سیستمی ، لطفا مجددا تالش فرمایید',
            500 => 'خطا در تایید تراکنش های خرد شده',
            501 => 'خطا در تایید تراکتش ، ویزگی تایید خودکار',
            502 => 'آدرس آی پی نا معتبر',
            503 => 'پذیرنده در حالت تستی می باشد ، مبلغ نمی تواند بیش از حد مجاز تایین شده برای پذیرنده تستی باشد',
            504 => 'خطا در بررسی الگوریتم شناسه پرداخت',
            505 => 'مدت زمان الزم برای انجام تراکنش تاییدیه به پایان رسیده است',
            506 => 'ذیرنده یافت نشد',
            507 => 'توکن نامعتبر/طول عمر توکن منقضی شده است',
            508 => 'توکن مورد نظر یافت نشد و یا منقضی شده است',
            509 => 'خطا در پارامترهای اجباری خرید تسهیم شده',
            510 => 'خطا در تعداد تسهیم | مبالغ کل تسهیم مغایر با مبلغ کل ارائه شده | خطای شماره ردیف تکراری',
            511 => 'حساب مسدود است',
            512 => 'حساب تعریف نشده است',
            513 => 'شماره تراکنش تکراری است',
            -20 => 'در درخواست کارکتر های غیر مجاز وجو دارد',
            -30 => 'تراکنش قبلا برگشت خورده است',
            -50 => 'طول رشته درخواست غیر مجاز است',
            -51 => 'در در خواست خطا وجود دارد',
            -80 => 'تراکنش مورد نظر یافت نشد',
            -81 => ' خطای داخلی بانک',
            -90 => 'تراکنش قبلا تایید شده است'
        );
        if (array_key_exists($status, $translations)) {
            throw new InvalidPaymentException($translations[$status]);
        } else {
            throw new InvalidPaymentException('خطای ناشناخته ای رخ داده است.');
        }
    }
```

![1](https://user-images.githubusercontent.com/37062636/102311182-a1a1d200-3f81-11eb-907d-abcde72c06f4.png)
این تصویر دلایل کالبک ناموفق از طرف بانکه.

![2](https://user-images.githubusercontent.com/37062636/102311221-b41c0b80-3f81-11eb-8a2a-7e50ae01522e.png)
اینم تصویر دلایل وریفای ناموفق هست.

شما دلایل وریفای ناموفق رو به من برمیگردونی طبق همین فانکشن بالا
ولی میخوام ببینم دلیل کالبک ناموفق رو هم برمیگردونی؟ روشی هست بتونم از همین پکیج دلیل کالبک ناموفق رو بگیرم؟

**Comment by khanzadimahdi** [comment]
مسیج بانک از طریق اکسپشن قابل دسترسی هست.

```php
$exception->getMessage();
```
