### ISSUE TITLE
کانفیگ بانک ملی(سداد)

### ISSUE THREAD

**Issue by mohammadsalmani28** [shetabit/multipay#37]
داخل کانفیگ سداد ارایه مربوط بهش از key های اشتباهی استفاده شده
چیزی که الان هست:
`
'apiPurchaseUrl' => 'https://sadad.shaparak.ir/vpg/api/v0/Request/PaymentRequest',
'apiPaymentUrl' => 'https://sadad.shaparak.ir/VPG/Purchase',
`

چیزی که باید باشه:
`'apiPaymentUrl' => 'https://sadad.shaparak.ir/vpg/api/v0/Request/PaymentRequest',
'apiPurchaseUrl' => 'https://sadad.shaparak.ir/VPG/Purchase',`

**Comment by khanzadimahdi** [comment]
لطفا فیکسش کنید و درخواست مرج شدن بدید

**Comment by mohammadsalmani28** [comment]
#38
