### ISSUE TITLE
ارسال شماره موبایل به سمت درگاه‌های پرداخت

### ISSUE THREAD

**Issue by aminmohammadmazreali** [shetabit/multipay#39]
## Detailed description

توی بیشتر درایورها تا اونجایی که من دیدم البته به جز زرین‌پال ارسال شماره موبایل به سمت درگاه انجام نمی‌شه! درگاه‌ها پشتیبانی نمیکنن یا کدش زده نشده؟

چون تا اونجایی که اطلاع دارم درگاه از شماره موبایل استفاده می‌کنه برای نشون دادن کارت‌های استفاده شده قبلی توسط این شماره

**Comment by khanzadimahdi** [comment]
اگه درگاه از شماره موبایل یا هر اطلاعات اضافه تری پشتیبانی کنه میتونید اون رو به صورت زیر بهش پاس بدید

```php
// At the top of the file.
use Shetabit\Multipay\Invoice;
...

// Create new invoice.
$invoice = new Invoice;

// Set invoice amount.
$invoice->amount(1000);

// Add invoice details: There are 4 syntax available for this.
// 1
$invoice->detail(['detailName' => 'your detail goes here']);
```

**Comment by khanzadimahdi** [comment]
درگاه هایی که از اطلاعات پاس داده شده پشتیبانی نکنن به صورت اتوماتیک توسط پکیج اون دیتا موقع ارسال درخواست به درگاه بانکی نادیده گرفته میشود

**Comment by aminmohammadmazreali** [comment]
خب الان در گاه اسان پرداخت از شماره موبایل پشتیبانی میکنه ولی چیزی که من داخل کدش دیدم اصلا شماره موبایلی ارسال نمیشه 

![image](https://user-images.githubusercontent.com/23165622/104565966-4b987b00-5662-11eb-97bf-e49a71db60b4.png)

داخل مستندات این درگاه نوشته که باید یک فیلد به اسم 
mobileap
همراه 
RefId 
ارسال بشه 

ولی چیزی ارسال نمیشه اینجا! درسته؟

**Comment by aminmohammadmazreali** [comment]
![image](https://user-images.githubusercontent.com/23165622/104566600-0a549b00-5663-11eb-9300-94a32fa61962.png)

**Comment by aminmohammadmazreali** [comment]
![image](https://user-images.githubusercontent.com/23165622/104566776-4556ce80-5663-11eb-9e80-7346fa700b07.png)


همین مورد در درگاه به‌پرداخت ملت

**Comment by khanzadimahdi** [comment]
در صورتی که توی  درایور درگاه این قابلیت پیاده سازی نشده نمیشه ازش استفاده کرد.

لطفا اون رو پیاده سازی کنید و درخواست مرج بدید.
