### ISSUE TITLE
مشکل در پرداخت صورت حساب

### ISSUE THREAD

**Issue by Blaster-777** [shetabit/multipay#41]
سلام من تراکنش رو ثبت میکنم تراکنش ساخته میشه و درخواست ثبت میشه ولی به صفحه پرداخت انتقال داده نمیشه و هیچ خطایی هم نشون نمیده

*php 8.0.0
*Ubuntu 18.04

**Comment by khanzadimahdi** [comment]
داکیومنت ها رو بخونید. کد رو درست ننوشتین

**Comment by khanzadimahdi** [comment]
اگه حس میکنید پکیج مشکل داره و طبق داکیومنت کارها رو انجام دادین لطفا بخش مرتبط کدهای خودتون رو قرار بدید تا بررسی کنم

**Comment by Blaster-777** [comment]
دقیقا کد های داکیومنت رو کپی کردم 

```
require_once("../../private_include/includes.php");

use Shetabit\Multipay\Invoice;
use Shetabit\Multipay\Payment;

$config = require('../../private_include/shetabit.php');
$payment = new Payment($config);
return  $payment->purchase(
    (new Invoice)->amount(1000), 
    function($driver, $transactionId) {
    	// Store transactionId in database.
        // We need the transactionId to verify payment in the future.
	}
)->pay();
```

**Comment by khanzadimahdi** [comment]
باید فرم ریدایرکت رو رندر کنید به صورت زیر

```php
->pay()->render();
```

**Comment by Blaster-777** [comment]
رندر هم کردم درست نشد به جای ری ترن فرم رو اکو کردم اوکی شد ممنون
