### ISSUE TITLE
Using Enviourment Variable

### ISSUE THREAD

**Issue by abilogos** [shetabit/multipay#5]
Using Enviourment Variable

Laravel Recommends to use .env file to store sensitive information like username / password etc ...
so i think its better to make them into the env file so a default user dosent need to publish any configuration and can run this via enviourment variable 

i want to change it and make a PR to solve this issue

##its a request for pull request.

## Context

its important in two way:
1. separation of Credential data from Code. (The Username password terminalid etc ) dosent need to transfer via git repo
2. The Publishing phase of config file is not an obligation any more.

**Comment by khanzadimahdi** [comment]
this package has written for PHP.

for Laravel see https://github.com/shetabit/payment

this package doesn't need to support Laravel environment vars, it is mainly for PHP usage.

**Comment by khanzadimahdi** [comment]
I will be nice if you add Paypal and other international payment gateways into this package.
