### ISSUE TITLE
Support currencies with precisions

### ISSUE THREAD

**Issue by parsagholipour** [shetabit/multipay#51]
https://github.com/shetabit/multipay/blob/652492cec95b70e0968b5c6ffd196d07dbed049c/src/Invoice.php
Currently the amount can only be Integer but many other currencies have precisions. In the case we need a driver having a currency with precisions, how should we fix this problem?

**Comment by khanzadimahdi** [comment]
what kind of currencies do you use? current gateways, all have fixed length amount (integer).

**Comment by parsagholipour** [comment]
We are developing a project which has a floating point number currency. I had the idea of using this package for the project and make the driver.

**Comment by khanzadimahdi** [comment]
using floating points in PHP is a bit risky! I recommend you to store numbers in string format and use `bcmath` or `decimal` addons for your calculations. (`decimal` is faster).

you can convert integer to float and send PR. i will review and merge.

**Comment by parsagholipour** [comment]
I use `number_format` function and round the result everywhere. 😉
I will send PR.

**Comment by khanzadimahdi** [comment]
round results! this could cause unwanted behaviors!

run the below code and see what happens

```php
<?php

$x = 1.1;
$y = 1.2;
$z = 1.3;

var_dump($x+$y == $z);
```

**Comment by parsagholipour** [comment]
Well logically 1.1 + 1.2 != 1.3
But I think you meant something like this:
```
<?php

$x = 1.4;
$y = 0.7;
$z = 2.1;


var_dump($x+$y == $z); // false
var_dump(number_format($x+$y, 2) == $z); // true, fix the issue
```

**Comment by rayansys** [comment]
`<?php

$x = 1.4;
$y = 0.7;
$z = 2.1;

$price =(float)str_replace(",","", number_format($x+$y, 2));

var_dump($x+$y == $z); // false
var_dump($price == $z); // true, fix the issue
`
