### ISSUE TITLE
داینامیکی کردن اطلاعات کانفیگ

### ISSUE THREAD

**Issue by mrmostafaeei** [shetabit/multipay#54]
امکانات به این خوبی گذاشتی ولی یکی از مهمترین قسمت ها وجود نداره، اینکه بشه داینامیکی یوزنیم و رمز یا مرچنت آی دی رو ست کرد روی Purchase
من مستقیم از درایور ها هم استفاده کردم تا بتونم تنظیمات رو با استفاده از stdClass ست کنم ولی بانک خطا میداد.
همین خطای بانک در حالتی که توی داکیومنت نوشته شده پیش برم بر طرف میشه. نتیجه گیری اینکه هیچ روشی وجودی نداره تا تنظیمات رو به شکل داینامیکی از دیتبایس بخونه و ست کنه روی دستور اتصال به بانک

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
قابلیت استفاده از کانفیگ به صورت داینامیک وجود داره. لطفا ابتدا داکیومنت ها رو بخونید.
طبق داکیومنت به صورت زیر میتونید عمل کنید

کانفیگ ها رو میتونید خودتون از دیتابیس لود کنید و استفاده کنید
</div>

```php
// Create new invoice.
$invoice = (new Invoice)->amount(1000);

// Purchase the given invoice with custom driver configs.
$payment->config('mechandId', 'your mechand id')->purchase(
    $invoice,
    function($driver, $transactionId) {
    // We can store $transactionId in database.
	}
);

// Also we can change multiple configs at the same time.
$payment->config(['key1' => 'value1', 'key2' => 'value2'])->purchase(
    $invoice,
    function($driver, $transactionId) {
    // We can store $transactionId in database.
	}
);
```
