### ISSUE TITLE
درگاه بانک پارسیان

### ISSUE THREAD

**Issue by rohi1386** [shetabit/multipay#59]
سلام و ممنون از زحماتتون- درگاه پارسیان یه ترمینال آی دی هم داره که شما تو پکیج اختصاص ندادید. چرا؟

**Comment by khanzadimahdi** [comment]
سلام وقت بخیر در حال حاضر کانفیگ زیر رو داریم

https://github.com/shetabit/multipay/blob/master/config/payment.php#L76

درگاه به درستی کار نمیکنه؟ در صورتی که مشکل داره لطفا اون رو فیکس کنید و درخواست مرج بدید

https://github.com/shetabit/multipay/blob/master/src/Drivers/Parsian/Parsian.php

کدهای درایور درگاه پارسیان رو میتونید توی مسیر بالا ببینید
