### ISSUE TITLE
Local driver for testing

### ISSUE THREAD

**Issue by hsharghi** [shetabit/multipay#66]
I've created a local driver for testing purposes. All the purchase flow can be tested and requires no real bank gateway. 
- Get transaction ID
- Redirect to payment form 
- Callback
- Verify payment 

Should I create a pull request for this repo or it should be as a separate package?

**Comment by khanzadimahdi** [comment]
cool, please make a pull request.
are you ok if I ask you to be one of the package maintainers? please mail me your mobile if you are keen at it.

my mail: khanzadimahdi[at]gmail.com

**Comment by hsharghi** [comment]
Sure. I'll make a pull request.

**Comment by hsharghi** [comment]
@khanzadimahdi Hey, 
Any lick adding local driver to payment package?

**Comment by khanzadimahdi** [comment]
I will add it as soon as I can. these days I am busy.
