### ISSUE TITLE
Return type of `toJson()` method is wrong

### ISSUE THREAD

**Issue by hsharghi** [shetabit/multipay#67]
Return type of `toJson()` method of `RedirectionForm` class is `\Illuminate\Http\JsonResponse` which is a defined class in `Laravel` framework. But this package is designed to use with plain `PHP` and is not dependent in any frameworks.

## Detailed description

Using `toJson()` method in plain `PHP` environment will result in a fatal error 

```
Fatal error: Uncaught Error: Class "Illuminate\Support\Facades\Response" not found
 in ..../multipay/src/RedirectionForm.php on line 187
```

to reproduce the error run this script:

```php
require_once 'vendor/autoload.php';

use Shetabit\Multipay\Invoice;
use Shetabit\Multipay\Payment;

$paymentConfig = require(dirname(__FILE__).'/vendor/shetabit/multipay/config/payment.php');

$payment = new Payment($paymentConfig);

$invoice = new Invoice();
$invoice->amount(10000);

echo $payment->purchase($invoice)->pay()->toJson();
```

## Possible implementation

I saw in comments history, response type has been changed to `\Illuminate\Http\JsonResponse` about 4 months ago in this commit https://github.com/shetabit/multipay/commit/bf834150f621c6dc1e543d7058c1d069e46a6535. This commit should be reverted and response type should be simple `json_encode` response, as this package is independent of any frameworks.

I think adding json type to header would be a good addition. Corrected method should be something like this

```php
    /**
     * Retrieve JSON format of redirection form.
     *
     * @param $options
     *
     * @return string|bool
     */
    public function toJson($options = JSON_UNESCAPED_UNICODE) : mixed
    {
        header('Content-Type: application/json');
        return json_encode($this, $options);
    }
```

## Your environment

* Version used (e.g. PHP 8.0.3):
* Operating system and version (masOS 10.15.4):

**Comment by khanzadimahdi** [comment]
please fix it and send a pull request. thanks.

I must write unit tests to prevent this kind of bug.

**Comment by hsharghi** [comment]
Yes it seems unit tests are really needed for this package. 
I think after adding `Local` driver (I hope tomorrow, fingers crossed!) adding unit test would be much easier.
