### ISSUE TITLE
Wrong parameter count for number_format() in local driver

### ISSUE THREAD

**Issue by programmerboy78** [shetabit/multipay#75]
<div dir="rtl">
من توی درایور local به ارور زیر خوردم که پس از بررسی دقیقتر تابع number_format متوجه شدم که این تابع ۱ یا ۲ یا ۴ پارامتر باید بگیره و در کد فعلی به تابع ۳ پارامتر پاس داده شده که توی ورژن php ۷.۲ به بالا به مشکل میخوره
</div>

![image](https://user-images.githubusercontent.com/22825860/122552854-172f4d80-d04c-11eb-8085-6638df166639.png)

**Comment by khanzadimahdi** [comment]
سلام وقت بخیر

درایور لوکال در حال حاضر به صورت تست ارائه شده و استیبل نیست و باید براش تست نوشته بشه

اگه باگ پیدا کردین و امکانش رو دارید فیکس کنید و درخواست مرج بدید

موفق و پیروز باشید

**Comment by programmerboy78** [comment]
> سلام وقت بخیر
> 
> درایور لوکال در حال حاضر به صورت تست ارائه شده و استیبل نیست و باید براش تست نوشته بشه
> 
> اگه باگ پیدا کردین و امکانش رو دارید فیکس کنید و درخواست مرج بدید
> 
> موفق و پیروز باشید

**Comment by programmerboy78** [comment]
<div dir="rtl">
لطفا pull request مربوط به fix این باگ رو accept کنید
</div>

https://github.com/shetabit/multipay/pull/76
