### ISSUE TITLE
شخصی سازی فرم ریدایرکت

### ISSUE THREAD

**Issue by ahbanavi** [shetabit/multipay#77]
سلام امکانش هست فرم ریدایرکت کاستومایز بشه؟ اگر آره چطور.
توی پروژه لاراول لومن دارم از همین پکیج استفاده می‌کنم

**Comment by iamammiin** [comment]
بله امکانش هست اگر ویو هارو پابلیش بکنین یه ویو ساخته میشه تو مسیر 

resources/vendor/shetabitPayment/redirectForm.blade.php

این ویو رو میتونین ویرایش کنین

**Comment by ahbanavi** [comment]
<div dir='rtl'>
این مال پکیج payment هستش که lumen رو ساپورت نمی‌کنه. <br />
من برای همین پکیج multipay منظورم بود. <br />
</div>

**Comment by ahbanavi** [comment]
توی سورس گشتم خودم و پیدا کردم راه حل رو:

```php
use Shetabit\Multipay\Payment;
Payment::setRedirectionFormViewPath(resource_path('redirectForm.php'));
```
خیلی خوب می‌شه اگر این توضیحات قابلیت رو توی داکیومنت این پکیج بیارین فکر کنم لازم باشه برای خیلیا.

**Comment by khanzadimahdi** [comment]
وقت بخیر. لطفا توی توسعه مشارکت داشته باشید. من به شدت سرم شلوغ هست این روزا

اگه امکانش هست به داکومنت ها مواردی که حس میکنید نیست رو اضافه کنید و درخواست مرج بدید.

ممنونم ازتون
