### ISSUE TITLE
درخواست مورد نظر يافت نشد.

### ISSUE THREAD

**Issue by farshidahmadianpin** [shetabit/multipay#78]
Shetabit\Multipay\Exceptions\PurchaseFailedException

Shetabit\Multipay\Drivers\Zarinpal\Zarinpal::purchase
root\vendor\shetabit\multipay\src\Drivers\Zarinpal\Zarinpal.php:83
من از لاراول 8 استفاده میکنم. وقتی از درگاه زرین پال استفاده میکنم اسن ارور رو میده
ممنون میشم راهنمایی کنین

**Comment by khanzadimahdi** [comment]
سلام. ای پی آی زرین پال تغییر کرده و به همین دلیل درایور زرین پال در پکیج باید یکسری تغییرات کنه تا متناسب با تغییرات اخیر زرین پال درست کار کنه. اگه امکانش هست فیکسش کنید و درخواست مرج بدید

**Comment by khanzadimahdi** [comment]
سلام درگاه زرین پال رو با توجه به اخرین ورژن ای پی آی که ارائه دادن بروز رسانی کردم. لطفا پکیج رو اپدیت کنید و فایل کانفیگ پکیج رو حذف کنید و دوباره پابلیش کنید
