### ISSUE TITLE
متوجه نشدم

### ISSUE THREAD

**Issue by vahidalvandi** [shetabit/multipay#81]
سلام چه فرقی بین دو تا پکیج است

shetabit/multipay
shetabit/payment

**Comment by khanzadimahdi** [comment]
اولی توی تمام پروژه هایی که با پی اچ پی نوشته شدن قابل استفاده هست

دومی یه رپر روی اولی هست که واسه لاراول ساخته شده

**Comment by vahidalvandi** [comment]
خب اینا باید یکی باشن
use Shetabit\Multipay\Invoice;
بیاد داخل
use Shetabit\payment\Invoice;

**Comment by khanzadimahdi** [comment]
shetabit/payment is a wrapper on shetabit/multipay. so it uses shetabit/multipay classes.
