### ISSUE TITLE
SOAP-ERROR: Encoding: Cannot find encoding  in Behpardakht

### ISSUE THREAD

**Issue by iamammiin** [shetabit/multipay#86]
SOAP-ERROR: Encoding: Cannot find encoding
 
show this error when using Behpardakht gateway

when updating to this version [v1.6.2](https://github.com/shetabit/multipay/releases/tag/v1.6.2)

@MeysamFallah @khanzadimahdi

**Comment by MeysamFallah** [comment]
Did you clear the cache after update with
`php artisan optimize `
or
`php artisan optimize:clear`
command?

**Comment by iamammiin** [comment]
my project deploys by docker after an updated project runs all this command : 
php artisan config:clear
php artisan config:cache

**Comment by iamammiin** [comment]
revert to previous version gateway is worked 

@MeysamFallah

**Comment by MeysamFallah** [comment]
if you revert to previous version it won't work with http2. Let me check it.
@iamammiin

**Comment by iamammiin** [comment]
> if you revert to previous version it won't work with http2. Let me check it.
> @iamammiin

ok, please check and fixed or say me to fix this. 
@MeysamFallah
