### ISSUE TITLE
زرین پال ریال دریافت میکنه

### ISSUE THREAD

**Issue by vahidalvandi** [shetabit/multipay#93]
سلام . دوست گرامی با توجه به اینکه ساختار پروژه بر اساس تومان است زرین پال به صورت ریال دریافت میکند
ضمن اینکه اگر این راهکار را اضافه کنید که خیلی عالی میشود

اگر ورودی کاربر ریال بود متد داشته باشیم که ورودی را در درگاه مورد نظر تبدیل کنیم مثلا اگر زرین پال تومان کار میکند و فروشگاه من ریال است ریال را بدهم و متد را هم ریال قرار بدهم اما در فرایندهای پرداخت ریال ورودی به تومان تبدیل شود 
و برای درگاه هایی که ورودی ریال دارند اگر وردی کاربر تومان بود متد را تومان قرار بدهد و تبدیل خودکار به ریال انجام شود

**Comment by khanzadimahdi** [comment]
توی پکیج تمامی درایور ها تومان است اگه جایی دیتا داره با ریال کار میکنه اون درایور باید اپدیت بشه

راه حلی که شما گفتین هیچ وقت انجام نمیشه چون پکیج واسه تمامی درگاه ها هست و پسفردا درگاه دلاری اضافه بشه نمیشه ریال بدیم خودش به دلار تبدیل کنه. پکیج تبدیل واحد پول نیست و تنها وظیفه ای که داره مدیریت درگاه پرداخت هست
