### ISSUE TITLE
Terminal is not active, please contact our support team.

### ISSUE THREAD

**Issue by farshidahmadianpin** [shetabit/multipay#94]
من از لاراول 8 استفاده میکنم
پکیجهای مولتی پی و پیمنت رو به اخرین ورژن آپدیت کردم
موقع استفاده از درگاه زرین پال این ارور رو میده:
```
Shetabit\Multipay\Exceptions\PurchaseFailedException

Terminal is not active, please contact our support team.
```

ممنون میشم راهنمایی کنین

**Comment by mohammadv184** [comment]
<div dir="rtl">
سلام
<br>
این خطا از وبسرویس زرین پال برمیگرده
<br>
که میگه مرچنت کد شما فعال نیست 
<br>
باید از خود زرین پال پیگیری کنید
<br>
</div>
<hr>
1-https://docs.zarinpal.com/paymentGateway/error.html
